name: PSScriptAnalyzer
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - "*.toml"
      - "*.gitkeep"
      - .editorconfig
      - .github/**
      - .gitignore
      - .gitattributes
      - .gitmodules
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - "*.toml"
      - "*.gitkeep"
      - .editorconfig
      - .github/**
      - .gitignore
      - .gitattributes
      - .gitmodules
jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell
        run: |
          apt-get update
          apt-get install -y wget
          wget --quiet https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell_7.5.4-1.deb_amd64.deb
          dpkg -i powershell_7.5.4-1.deb_amd64.deb
          apt-get install -f
          rm powershell_7.5.4-1.deb_amd64.deb
      - name: Run PSScriptAnalyzer
        uses: https://github.com/microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./
          recurse: true
          settings: ./PSScriptAnalyzerSettings.psd1
          enableExit: true
          output: results.sarif
