---
name: PSScriptAnalyzer

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - "*.toml"
      - "*.gitkeep"
      - .editorconfig
      - .github/**
      - .gitignore
      - .gitattributes
      - .gitmodules
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - "*.toml"
      - "*.gitkeep"
      - .editorconfig
      - .github/**
      - .gitignore
      - .gitattributes
      - .gitmodules

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by upload-sarif to get the Action run status
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./
          recurse: true
          output: results.sarif
          settings: ./PSScriptAnalyzerSettings.psd1

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
